feat: python server
Safe-DS/Runner pull request #6
Opened 2023-11-06 14:22 UTC by WinPlay02

- executes compiled safe-ds code in memory (using a finder / loader) with a separate globals dictionary
- allows connections via websocket (and http)
- listens on a provided port (default 5000)
- uses flask and flask-sock for HTTP and WS
- uses gevent as WSGI implementation

2023-11-27 18:06 UTC, lars-reimann commented
I have no experience with this. Maybe the [pytest-cov documentation](https://pytest-cov.readthedocs.io/en/latest/subprocess-support.html#) helps.

2023-11-28 01:23 UTC, WinPlay02 commented
It seems to be a problem only on Windows, as the CI passes. I annotated the tests skip execution on Windows for now.
Although they work when coverage calculation does not include multiprocessing (in `.coveragerc`, see above).

2023-11-29 09:44 UTC, lars-reimann commented
> It seems to be a problem only on Windows, as the CI passes. I annotated the tests skip execution on Windows for now.
Although they work when coverage calculation does not include multiprocessing (in .coveragerc, see above).

I can't reproduce this on a Windows machine. `pytest --cov=safeds_runner --cov-report=xml` works fine.

2023-11-29 11:17 UTC, lars-reimann requested changes

2023-11-29 11:17 UTC, lars-reimann commented on src/safeds_runner/server/main.py
> +    :param testing Whether the app should run in a testing context
Docstrings should use the Numpydoc style:

* [Specification](https://numpydoc.readthedocs.io/en/latest/format.html)
* [Project setup (4. item)](https://runner.safeds.com/en/stable/development/environment/#project-setup)
* [Project guidelines](https://library.safeds.com/en/stable/development/project_guidelines/#docstrings) (other repo, will be copied here too)

2023-11-29 11:17 UTC, lars-reimann commented on src/safeds_runner/server/__init__.py
> +"""Infrastructure for dynamically running Safe-DS pipelines and communication with the vscode extension."""
```suggestion
"""Infrastructure for dynamically running Safe-DS pipelines and communication with the VS Code extension."""
```

2023-11-30 00:20 UTC, WinPlay02 commented
I think I addressed all the suggestions. Now, the `PipelineManager` class takes the place of most of the global variables. It is created at startup and used in the websocket session.
But I couldn't get rid of the `current_pipeline` global in `pipeline_manager.py` as it is used for saving placeholders.

2023-11-30 10:43 UTC, lars-reimann requested changes
Looks great overall. I just have some minor requests.

2023-11-30 10:43 UTC, lars-reimann commented on src/safeds_runner/server/pipeline_manager.py
> +        self.messages_queue_thread.start()
Add leading `_` to the names of attributes that should be internal to the class.

2023-11-30 10:43 UTC, lars-reimann commented on src/safeds_runner/server/pipeline_manager.py
> +        self.process = multiprocessing.Process(target=self._execute, daemon=True)
Add leading `_` to the names of attributes that should be internal to the class.

2023-11-30 10:43 UTC, lars-reimann commented on src/safeds_runner/server/pipeline_manager.py
> +        return object_name
Can also be expressed using [pattern matching](https://stackoverflow.com/a/67524642). It's up to you whether you want to change it or leave it.

2023-11-30 13:57 UTC, lars-reimann approved these changes
Great contribution, thanks! 👍

2023-11-30 13:58 UTC, merged

2023-11-30 14:12 UTC, lars-reimann commented
:tada: This PR is included in version 0.2.0 :tada:

The release is available on:
- `v0.2.0`
- [GitHub release](https://github.com/Safe-DS/Runner/releases/tag/v0.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: